# Generated by Django 5.1.3 on 2024-11-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentFund',
            fields=[
                ('fund_id', models.AutoField(primary_key=True, serialize=False)),
                ('fund_name', models.CharField(max_length=100)),
                ('fund_manager_name', models.CharField(max_length=100)),
                ('fund_desc', models.TextField()),
                ('fund_net_asset_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fund_created_date', models.DateField(auto_now_add=True)),
                ('fund_performance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
